### PR TITLE
Daryl's version of the primes test

### PR DESCRIPTION
**Pull request by ngzax**
I was feeling my oats and had a bit of time on the train a couple of weeks back and I thought I would try a solution to our standard primes test using python generators.

Obviously, this would be tough to come up by a candidate on a whiteboard... I had to look up docs on itertools  for islice() and count() or I wouldn't have been able to complete it.

But I still think its a pretty cool solution overall. With tests. 😄

### CODE REVIEW

**Comment by ngzax** [comment]
@ethanmcc might want to review.

**Comment by ethanmcc** [comment]
@ngzax very cool. 👍

**Comment by ngzax** [comment]
So... @aheld .... a little merge love? ❤️

**Comment by aheld** [comment]
Sure!

thanks!

**Pull request merged**
